### ISSUE TITLE
[Issue]: `hipResourceDesTocudaResourceDes` returns a pointer to a local variable

### ISSUE THREAD

**Issue by joerowell** [ROCm/hipother#2]
### Problem Description

When compiling against the HIP version included with `rocm-6.0.0` and earlier (originating with [this](https://github.com/ROCm/hipother/commit/452c1060f3efffa77b902cca4710e7418fc003c6)) commit, I see that the `hipResourceDesTocudaResourceDes` function returns a pointer to a local variable. That is, the return value is declared locally:

https://github.com/ROCm/hipother/blob/75ef32dfe9fa714d4716d1b5fd7d537a2e2837e8/hipnv/include/hip/nvidia_detail/nvidia_hip_runtime_api.h#L481

But returned via its address:

https://github.com/ROCm/hipother/blob/75ef32dfe9fa714d4716d1b5fd7d537a2e2837e8/hipnv/include/hip/nvidia_detail/nvidia_hip_runtime_api.h#L507

This is undefined behaviour, as per [6.2.4](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf) (paragraph 2) of the C17 programming language standard.

### Operating System

-

### CPU

-

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.0.0

**Comment by servusdei2018** [comment]
Fixed in 1287d7e
